### PR TITLE
fix(Circle): the gradient color is incorrect

### LINKED ISSUE #7905: [Bug Report] 紧急 紧急，Circle 环形进度条的渐变色有bug，设置不了
设备 / 浏览器
chrome

Vant 版本
∧2.11

重现链接
https://youzan.github.io/vant/#/zh-CN/circle

描述问题
像是v2.11.2新增Color的@circle-color变量导致

### PR DESCRIPTION
**Pull request by John60676**
fix #7905

2.x has the same problem, I can submit another PR if necessary

### CODE REVIEW

**Review by chenjiahan — APPROVED** [review]

**Comment by chenjiahan** [comment]
👏👏 2.x 也可以提一个喔

File: src/circle/index.tsx [hunk 1]
```diff
@@ -110,7 +112,7 @@ export default createComponent({
           d={path.value}
           style={style}
           class={bem('hover')}
-          stroke={isObject(color) ? `url(#${id})` : color}
+          stroke={color}
```
Comment (John60676) [inline src/circle/index.tsx:115]: @chenjiahan `stroke={color}` 这个属性应该可以去掉吧，内联里面有了
